# Generated by Django 5.0.4 on 2024-04-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspaper",
            name="topics",
        ),
        migrations.AddField(
            model_name="newspaper",
            name="topics",
            field=models.ManyToManyField(to="agency.topic"),
        ),
    ]
